/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AeSvgtestComponent {
    'aeicon': string;
    /**
    * Title for the panel
    */
    'aetitle': string;
    /**
    * SVG content
    */
    'svgcontent': string;
    /**
    * Show/Hide the panel
    */
    'toggle': () => Promise<void>;
  }
}

declare global {


  interface HTMLAeSvgtestComponentElement extends Components.AeSvgtestComponent, HTMLStencilElement {}
  var HTMLAeSvgtestComponentElement: {
    prototype: HTMLAeSvgtestComponentElement;
    new (): HTMLAeSvgtestComponentElement;
  };
  interface HTMLElementTagNameMap {
    'ae-svgtest-component': HTMLAeSvgtestComponentElement;
  }
}

declare namespace LocalJSX {
  interface AeSvgtestComponent extends JSXBase.HTMLAttributes<HTMLAeSvgtestComponentElement> {
    'aeicon'?: string;
    /**
    * Title for the panel
    */
    'aetitle'?: string;
    /**
    * SVG content
    */
    'svgcontent'?: string;
  }

  interface IntrinsicElements {
    'ae-svgtest-component': AeSvgtestComponent;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


